version: "3.5"
services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
  pet-bokeh:
    build:
      context: ./pet-bokeh
    ports:
      - "8002:8000"
  face-emotion:
    build:
      context: ./face-emotion
    ports:
      - "8003:8000"
  triton:
    image: nvcr.io/nvidia/tritonserver:22.06-py3
    env_file:
      - .aws.env
    ports:
      - "8000:8000"
    command:
      [
        "tritonserver",
        "--model-repository=s3://triton-repository/models/"
      ]
