name: "face-emotion"
platform: "tensorflow_savedmodel"
input [
  {
    name: "conv2d_8_input"
    data_type: TYPE_FP32
    dims: [-1,48,48,1]
  }
]
output {
    name: "dense_5"
    data_type: TYPE_FP32
    dims: [-1,7]
  }